MMSLHMS/MMSLHMS/Controllers/DiagnosticController.cs
using HMSBLL;
using HMSBO.Models;
using HMSBO.ViewModels;
//using Microsoft.Reporting.WinForms;
using Microsoft.Reporting.WebForms;
using MMSLHMS.CustomFiles.Filters;
using MMSLHMS.DAL;
using MMSLHMS.DAL.Security;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMSBO.ReportModels;
using System.Drawing;
using PagedList.Mvc;
using PagedList;

namespace MMSLHMS.Controllers
{
    [CustomAuthorize]
    public class DiagnosticController : BaseController
    {
        // GET: Diagnostic
        private DataContext db = new DataContext();

        [HttpGet]
        public ActionResult GetInvestigationList(string InvestigationName, int? Fees)
        {
            var investigations = (from diag in db.tblInvestigations
                                  join org in db.tblOrganizations on diag.OrgId equals org.OrgId
                                  where diag.OrgId == User.OrgId && (InvestigationName == null || InvestigationName.Trim() == "" || diag.Name.ToLower().Contains(InvestigationName.ToLower().Trim()))
                                  && (Fees == null || Fees == 0 || diag.Fee == Fees)
                                  select new { diag.Id, diag.Name, diag.Fee,diag.RefFee, diag.EntryUser, diag.EntryDate, diag.UpdateBy, diag.UpdateDate, org.OrgId, OrgName = org.Name, BranchId = diag.BranchId }).ToList();

            List<VmInvestigation> invList = new List<VmInvestigation>();
            foreach (var item in investigations)
            {
                VmInvestigation inv = new VmInvestigation();
                inv.Id = item.Id;
                inv.Name = item.Name;
                inv.Fee = item.Fee;
                inv.RefFee = item.RefFee;
                inv.EntryUser = item.EntryUser;
                inv.EntryDate = item.EntryDate;
                inv.UpdateBy = item.UpdateBy;
                inv.UpdateDate = item.UpdateDate;
                inv.OrgId = item.OrgId;
                inv.OrgName = item.OrgName;
                inv.BranchId = item.BranchId;
                invList.Add(inv);
            }

            if (InvestigationName == null && Fees == null)
            {
                return View(invList);
            }
            else
            {
                return Json(invList, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult SaveInvestigation(VmInvestigation model)
        {
            bool IsSuccess = false;
            if (ModelState.IsValid)
            {
                if (model.Id <= 0)
                {
                    Investigation inv = new Investigation();
                    //inv.Name = model.Name;
                    inv.Fee = model.Fee;
                    inv.OrgId = User.OrgId;
                    inv.RefFee = model.RefFee;
                    inv.EntryUser = User.UserName;
                    inv.EntryDate = DateTime.Now;
                    db.tblInvestigations.Add(inv);
                    IsSuccess = true;
                }
                else if (model.Id > 0)
                {
                    var invInDb = db.tblInvestigations.FirstOrDefault(inv => inv.Id == model.Id);
                    if (invInDb != null)
                    {
                        //invInDb.Name = model.Name;
                        invInDb.Fee = model.Fee;
                        invInDb.UpdateBy = User.UserName;
                        invInDb.UpdateDate = DateTime.Now;
                        invInDb.RefFee = model.RefFee;
                        IsSuccess = true;
                    }
                }
                db.SaveChanges();
            }
            return Json(IsSuccess);
        }
        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult SaveInvestigationFromChart(List<VmInvestigation> model)
        {
            bool IsSuccess = false;
            try
            {
                if (ModelState.IsValid)
                {
                    foreach (var item in model)
                    {
                        Investigation investigation = new Investigation()
                        {
                            Name = item.Name,
                            Fee = item.Fee,
                            RefFee=item.RefFee,
                            OrgId = User.OrgId,
                            ChartId = item.ChartId,
                            EntryUser = User.UserName,
                            EntryDate = DateTime.Now
                        };
                        db.tblInvestigations.Add(investigation);
                    }
                    db.SaveChanges();
                    IsSuccess = true;
                }
            }
            catch (Exception ex)
            {

            }
            finally
            {

            }
            return Json(IsSuccess);
        }

        [HttpGet]
        public JsonResult GetInvestigationById(int id)
        {
            var inv = db.tblInvestigations.Find(id);
            return Json(inv, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetReferrerList(string ReferrerName, string ReferrerAddress, string ReferrerMobile)
        {
            var data = (from inv in db.tblInvestigatinReferrer
                        join org in db.tblOrganizations
                        on inv.OrgId equals org.OrgId
                        where org.OrgId == User.OrgId
                        && (ReferrerName == null || ReferrerName.Trim() == "" || inv.Name.ToLower().Contains(ReferrerName.ToLower().Trim()))
                        && (ReferrerAddress == null || ReferrerAddress.Trim() == "" || inv.Address.ToLower().Contains(ReferrerAddress.Trim().ToLower()))
                        && (ReferrerMobile == null || ReferrerMobile.Trim() == "" || inv.PhoneNumber.ToLower().Contains(ReferrerMobile.Trim().ToLower()))
                        select new { Id = inv.Id, inv.Name, inv.Address, inv.PhoneNumber, inv.EntryUser, inv.EntryDate, inv.UpdateBy, inv.UpdateDate, OrgName = org.Name, OrgId = org.OrgId }).ToList();

            List<VmInvestigationReferrar> invList = new List<VmInvestigationReferrar>();
            foreach (var item in data)
            {
                VmInvestigationReferrar invRef = new VmInvestigationReferrar();
                invRef.Id = item.Id;
                invRef.Name = item.Name;
                invRef.Address = item.Address;
                invRef.PhoneNumber = item.PhoneNumber;
                invRef.OrgId = item.OrgId;
                invRef.OrgName = item.OrgName;
                invRef.EntryUser = item.EntryUser;
                invRef.EntryDate = item.EntryDate;
                invRef.UpdateBy = item.UpdateBy;
                invRef.UpdateDate = item.UpdateDate;
                invList.Add(invRef);
            }
            if (ReferrerName == null && ReferrerAddress == null && ReferrerMobile == null)
            {
                return View(invList);
            }
            else
            {
                return Json(invList, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult SaveReferrer(VmInvestigationReferrar model)
        {
            bool IsSuccess = false;
            if (ModelState.IsValid)
            {
                if (model.Id <= 0)
                {
                    InvestigationReferrer invRef = new InvestigationReferrer();
                    invRef.Name = model.Name;
                    invRef.Address = model.Address;
                    invRef.PhoneNumber = model.PhoneNumber;
                    invRef.EntryUser = User.UserName;
                    invRef.EntryDate = DateTime.Now;
                    invRef.OrgId = User.OrgId;
                    db.tblInvestigatinReferrer.Add(invRef);
                    IsSuccess = true;
                }
                else if (model.Id > 0)
                {
                    var invRefInDb = db.tblInvestigatinReferrer.Find(model.Id);
                    if (invRefInDb != null)
                    {
                        invRefInDb.Name = model.Name;
                        invRefInDb.Address = model.Address;
                        invRefInDb.PhoneNumber = model.PhoneNumber;
                        invRefInDb.UpdateBy = User.UserName;
                        invRefInDb.UpdateDate = DateTime.Now;
                        IsSuccess = true;
                    }
                }
                db.SaveChanges();
            }
            return Json(IsSuccess);
        }

        [HttpGet]
        public JsonResult GetReferrerById(int id)
        {
            var referrer = db.tblInvestigatinReferrer.Find(id);
            return Json(referrer, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetBillInformation()
        {
            var billInfoData = (from bi in db.tblDiagnosticBillInfo
                                    //join bd in db.tblDiagnosticBillDetails on bi.Id equals bd.BillInfoId
                                join org in db.tblOrganizations on bi.OrgId equals org.OrgId
                                where org.OrgId == User.OrgId
                                select new { bi.Id, bi.InvoiceNo, bi.PatientId, bi.OrgId, OrgName = org.Name, bi.PatientName, bi.Address, bi.MobileNo, bi.Year, bi.Sex, bi.NetAmount, bi.Status, bi.ReceivedAmount, bi.DueAmount, bi.DiscountAmount, bi.DiscountPercent, bi.PaymentMode }).ToList();

            List<VmDiagnosisBillInfo> billInfos = new List<VmDiagnosisBillInfo>();
            foreach (var item in billInfoData)
            {
                VmDiagnosisBillInfo billInfo = new VmDiagnosisBillInfo();
                billInfo.Id = item.Id;
                billInfo.InvoiceNo = item.InvoiceNo;
                billInfo.PatientId = item.PatientId;
                billInfo.OrgId = item.OrgId;

MMSLHMS/MMSLHMS/Views/Diagnostic/CreateInvestigation.cshtml
@model HMSBO.ViewModels.VmInvestigation

@{
    ViewBag.Title = ViewBag.OPTitle;
}

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-4"><a class="btn btn-success" href="/Diagnostic/GetInvestigationList">Back To List</a></div>
            <div class="col-md-4"><h4>@ViewBag.OPTitle</h4></div>
            <div class="col-md-4"><button class="btn btn-primary float-right" form="frmInv"><i class="fa fa-save"></i>&nbsp;Save</button></div>
        </div>
        <br />
    </div>
    <div class="col-md-12" style="overflow-y:scroll;height:600px">
        @using (Html.BeginForm("SaveInvestigation", "Diagnostic", FormMethod.Post, new { @id = "frmInv" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-row">
                <div class="form-group col-md-4">
                    @Html.LabelFor(m => m.Name, string.Format(@"Investigatin Name:"), new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10 input-group">
                        @Html.EditorFor(m => m.Name, new { @class = "form-control form-control-sm" })
                        <span class="text-danger">*</span>
                    </div>
                    @Html.ValidationMessageFor(m => m.Name, null, new { @class = "error" })
                </div>
                <div class="form-group col-md-4">
                    <div class="form-group col-md-4">
                        @Html.LabelFor(m => m.Fee, string.Format(@"Investigatin Name:"), new { @class = "control-label col-md-10 font-weight-bold" })
                        <div class="col-md-10 input-group">
                            @Html.EditorFor(m => m.Fee, new { @class = "form-control form-control-sm",@type="number" })
                            <span class="text-danger">*</span>
                        </div>
                        @Html.ValidationMessageFor(m => m.Fee, null, new { @class = "error" })
                    </div>
                </div>
                <div class="form-group col-md-4"></div>
            </div>
            <div class="form-row"></div>
            <div class="form-row"></div>
        }
    </div>
</div>

MMSLHMS/MMSLHMS/Views/Diagnostic/GetDiagnosticDueList.cshtml
@{
    ViewBag.Title = "Diagnostic Bill-Due Adjustment";
}

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <form id="searchForm">
                    @Html.AntiForgeryToken()
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <div class="col-md-12">
                                <h4 class="text-center">Bill Due Adjustment:</h4>
                            </div>
                            <hr />
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label class="control-label col-md-12 font-weight-bold">Invoice:</label>
                            <div class="col-md-12">
                                @Html.TextBox("InvoiceNo", null, new { @class = "form-control form-control-sm", placeholder = "Search By Invoice" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <label class="control-label col-md-12 font-weight-bold">Patient Name:</label>
                            <div class="col-md-12">
                                @Html.TextBox("PatientName", null, new { @class = "form-control form-control-sm", placeholder = "Search By Patient Name" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <label class="control-label col-md-12 font-weight-bold">Mobile No:</label>
                            <div class="col-md-12">
                                @Html.TextBox("MobileNo", null, new { @class = "form-control form-control-sm", placeholder = "Search By Mobile No" })
                            </div>
                        </div>
                    </div>
                    <hr />
                </form>
            </div>
            <br />
        </div>
    </div>
    <div class="col-md-12" id="data-Container">
        @{ Html.RenderAction("GetDueList", "Diagnostic"); }@* Data Body *@
    </div>
</div>

<div class="modal fade" id="modalDueAdj">
    <div class="modal-dialog modal-lg">
        <div class="modal-content ">
            <div class="modal-header  btn-success">
                <h4 class="modal-title" id="modalHeading">Due Adjustment</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form id="frmDueAdj" autocomplete="off">
                <input type="hidden" id="hdfBillInfoId" value="0" />
                <input type="hidden" id="hdfInvoiceNo" value="" />
                @Html.AntiForgeryToken()
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <div class="input-group">
                                <label><b>Invoice No:</b></label> &nbsp;
                                <label id="lblInvoiceNo"></label>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <div class="input-group">
                                <label><b>Patient Name:</b></label> &nbsp;
                                <label id="lblPatientName"></label>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <div class="input-group">
                                <label><b>Mobile No:</b></label> &nbsp;
                                <label id="lblMobileNo"></label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <div class="input-group">
                                <label><b>Net Amount:</b></label> &nbsp;
                                <label id="lblNetAmount"></label>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <div class="input-group">
                                <label><b>Received Amount:</b></label> &nbsp;
                                <label id="lblPrevReceAmt"></label>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <div class="input-group">
                                <label><b>Due Amount:</b></label> &nbsp;
                                <label id="lblDueAmount"></label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-5 col-md-offset-7">
                            <div class="input-group">
                                <label for="txtNewReceiveAmt"><b>New Receive Amount:</b></label>&nbsp;
                                <input id="txtNewReceiveAmt" class="form-control form-control-sm" type="number" />
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-offset-8 col-md-4">
                            <div class="input-group">
                                <label><b>Return Amount:</b></label> &nbsp;
                                <label id="lblReturnAmt">0</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <span class="hide error" id="errorTxt"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal" data-target="#modalDueAdj"><i class="fa fa-remove"></i> Cancel</button>
                    <button type="submit" id="btnSubmit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">

        var txtInvoiceNo = $("#InvoiceNo");
        var txtPatientName = $("#PatientName");
        var txtMobileNo = $("#MobileNo");
        var lblInvoiceNo = $("#lblInvoiceNo");
        var lblPatientName = $("#lblPatientName");
        var lblMobileNo = $("#lblMobileNo");
        var lblNetAmount = $("#lblNetAmount");
        var lblPrevReceAmt = $("#lblPrevReceAmt");
        var lblDueAmount = $("#lblDueAmount");
        var txtNewReceiveAmt = $("#txtNewReceiveAmt");
        var lblReturnAmt = $("#lblReturnAmt");
        var hdfBillInfoId = $("#hdfBillInfoId");
        var hdfInvoiceNo = $("#hdfInvoiceNo");
        var btnSubmit = $("#btnSubmit");
        var errorTxt = $("#errorTxt");

        function ajaxCalling() {
            var invoiceNo = txtInvoiceNo.val().trim();
            var patientName = txtPatientName.val().trim();
            var mobileNo = txtMobileNo.val().trim();

            $.when(getReqWithData('html', 'GET', '/Diagnostic/GetDueList', { invoiceNo: invoiceNo, mobileNo: mobileNo, patientName: patientName })).then(function (res,status) {
                $("#data-Container").html(res)
            }).fail(function (err) {
                console.log(err);
            })
        }

        txtInvoiceNo.on("keyup", function () {
            ajaxCalling();
        })
        txtPatientName.on("keyup", function () {
            ajaxCalling();
        })
        txtMobileNo.on("keyup", function () {
            ajaxCalling();
        })

        function clearCtrl() {
            lblInvoiceNo.text('');
            lblPatientName.text('');
            lblMobileNo.text('');
            lblNetAmount.text('');
            lblPrevReceAmt.text('');
            lblDueAmount.text('');
            lblReturnAmt.text('0');
            txtNewReceiveAmt.val('0');
            errorTxt.addClass("hide");
            btnSubmit.prop("disabled", false);
        }

        function OpenModal() {
            clearCtrl();
            $("#modalDueAdj").modal();
        }

        $(document).on("click", "a.data-item", function (e) {
            e.preventDefault();
            OpenModal();

            var parentTr = $(this).parent().parents('tr');
            var billId = parentTr.find('td:eq(0)').html();
            var invoice = parentTr.find('td:eq(2)').html();
            var patient = parentTr.find('td:eq(3)').html();
            var mobile = parentTr.find('td:eq(4)').html();
            var netAmt = parentTr.find('td:eq(6)').html();
            var receAmt = parentTr.find('td:eq(7)').html();
            var dueAmt = parentTr.find('td:eq(8)').html();

            hdfBillInfoId.val(billId);
            hdfInvoiceNo.val(invoice);
            lblInvoiceNo.text(invoice);
            lblPatientName.text(patient);
            lblMobileNo.text(mobile);
            lblNetAmount.text(netAmt);
            lblPrevReceAmt.text(receAmt);
            lblDueAmount.text(dueAmt);
        })

        txtNewReceiveAmt.on("keyup", function () {
            lblReturnAmt.text('0');
            if (TryParseFloat(txtNewReceiveAmt.val(), 0) > 0)
            {
                var rtnAmt = parseFloat(txtNewReceiveAmt.val()) - parseFloat(lblDueAmount.text())
                lblReturnAmt.text(rtnAmt);
            }
        })

        function validateForm() {
            var isValid = true;
            errorTxt.addClass("hide");

            if (TryParseInt(hdfBillInfoId.val().trim(), 0) == 0)
            {
                errorTxt.text('Bill Id not found. Please Refresh the page and retry.');
                isValid = false;
            }
            if (hdfInvoiceNo.val().trim() == 0) {
                errorTxt.text(' Invoice No. not found. Please Refresh the page and retry.');
                isValid = false;
            }
            if (txtNewReceiveAmt.val().trim() == '' || txtNewReceiveAmt.val().trim() == '0')
            {
                errorTxt.text('New receive amount is required');
                isValid = false;
            }
            if (TryParseFloat(lblDueAmount.text().trim(), 0) <= 0)
            {
                errorTxt.text('Due amount should be grater than 0');
                isValid = false;
            }
            if (TryParseFloat(lblDueAmount.text().trim(), 0) != TryParseFloat(txtNewReceiveAmt.val().trim(),0)) {
                errorTxt.text('New Receive amount should be equal to Due amount');
                isValid = false;
            }
            if (!isValid)
                errorTxt.removeClass("hide");
            return isValid;
        }

        btnSubmit.on("click", function (e) {
            e.preventDefault();
            btnSubmit.prop("disabled", true);
            if (validateForm())
            {
                var data = JSON.stringify({ id: parseInt(hdfBillInfoId.val()), invoiceNo: hdfInvoiceNo.val(), mobileNo: lblMobileNo.text(), receiveAmount: parseFloat(txtNewReceiveAmt.val()), dueAmount: parseFloat(lblDueAmount.text()) });
                console.log(data);
                $.when(postReqWithToken(dataType.applicationJson, dataType.json, 'POST', '/Diagnostic/SaveBillDueAmount', data, getToken())).then(function (res, status) {
                    btnSubmit.prop("disabled", false);
                    if (res.isSuccess) {
                        alert(execuStatus.successSave);
                        $("#modalDueAdj").modal("toggle");

                        txtInvoiceNo.val('');
                        txtPatientName.val('');
                        txtMobileNo.val('');

                        // Report 
                        var pdfWindow = window.open("", "_blank");
                        pdfWindow.document.write("<embed width='100%' height='100%' src='" + encodeURI(res.file) + "'></embed>");
                        download(res.file, res.fileName, "application/pdf");

                        // Loading Data
                        ajaxCalling()
                    }
                    else {
                        alert(execuStatus.fail);
                    }
                }).fail(function (err) {
                    console.log(err);
                }) 
            }
            else {
                btnSubmit.prop("disabled", false);
            }
        })

        
    </script>    
}

MMSLHMS/MMSLHMS/Views/Diagnostic/_GetDateRageWiseBillInfo.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<HMSBO.ViewModels.vmDianosticBillDueAdjustment>

@{
    Layout = null;
    int count = 0;
}

<div class="col-md-12 dvDateRangeWiseBillInfo">
    <table class="table table-sm table-bordered table-responsive-lg table-hover" id="tblDateRangeWiseBillInfo">
        <thead class="btn-info btn-sm">
            <tr>
                <th class="hide">Id</th>
                <th>SL No</th>
                <th>Invoice No</th>
                <th>Patient Name</th>
                <th>Mobile No</th>
                <th>Ref. By</th>
                <th>Total Test</th>
                <th>Sub Total</th>
                <th>Discount</th>
                <th>Net Amount</th>
                <th class="hide">Received Amount</th>
                <th>Ref. Fee</th>
                <th>Due Amount</th>
                <th>Bill Date</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    count = count + 1;
                    string date = string.Format("{0:dd-MMM-yyyy}", Convert.ToDateTime(item.EntryDate.ToString()));
                    <tr>
                        <td class="hide">@item.Id</td>
                        <td class="text-center">@count</td>
                        <td>@item.InvoiceNo</td>
                        <td>@item.PatientName</td>
                        <td>@item.MobileNo</td>
                        <td>@item.RefName</td>
                        <td>@item.InvestigationQty</td>
                        <td>@item.SubTotal</td>
                        <td>@item.DiscountAmount</td>
                        <td align="right">@item.NetAmount</td>
                        <td align="right" class="hide">@item.ReceiveAmount</td>
                        <td align="right">@item.TotalRefFee</td>
                        <td align="right">@item.DueAmount</td>
                        <td>@date</td>
                        <td class="text-center">@item.Status</td>
                        <td style="width:12%" class="text-center">
                            <a href="#" data-edit-item="@item.Id" class="btn btn-circle btn-success btn-sm data-DateRange-item" title="View Details"><i class="fa fa-eye"></i></a>
                            <a href="#" data-del-item="@item.Id" class="btn btn-circle btn-danger btn-sm data-DateRange-drop hide" title="Drop Invoice"><i class="fa fa-trash"></i></a>
                            <a href="#" data-print-item="@item.Id" class="btn btn-circle btn-primary btn-sm data-DateRange-print" title="Print Preview"><i class="fa fa-print"></i></a>
                        </td>
                    </tr>
                }
            }
            else
            {
                count = 0;
                <tr class="text-danger text-center empty-row">
                    <td colspan="13">No Data Found</td>
                </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager(Model, page => Url.Action("", new { page } ), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
</div>

MMSLHMS/MMSLHMS/Views/Diagnostic/_GetDueList.cshtml
@model IEnumerable<HMSBO.ViewModels.vmDianosticBillDueAdjustment>
@{
    Layout = null;
    int count = 0;
}

<div class="col-md-12">
    <table class="table table-sm table-bordered table-responsive-lg table-hover">
        <thead class="btn-info">
            <tr>
                <th class="hide">Id</th>
                <th>SLNo</th>
                <th>Invoice No</th>
                <th>Patient Name</th>
                <th>Mobile No</th>
                <th>Total Test</th>
                <th>Net Amount</th>
                <th>Receive Amount</th>
                <th>Due Amount</th>
                <th>Bill Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    count = count + 1;
                    <tr>
                        <td class="hide">@item.Id</td>
                        <td class="text-center">@count</td>
                        <td>@item.InvoiceNo</td>
                        <td>@item.PatientName</td>
                        <td>@item.MobileNo</td>
                        <td>@item.InvestigationQty</td>
                        <td align="right">@item.NetAmount</td>
                        <td align="right">@item.ReceiveAmount</td>
                        <td align="right">@item.DueAmount</td>
                        <td>@Html.DisplayFor(model => item.EntryDate)</td>
                        <td><a href="#" data-edit-item="@item.Id" class="btn btn-success btn-sm data-item"><i class="fa fa-money-bill"></i> Due Adjust</a></td>
                    </tr>
                }
            }
            else
            {
                count = 0;
                <tr class="text-danger text-center">
                    <td colspan="10">No Data Found</td>
                </tr>
            }
        </tbody>
    </table>

</div>

MMSLHMS/MMSLHMS/Views/Diagnostic/_GetOtherProfessional.cshtml
@model IEnumerable<HMSBO.ViewModels.VmOtherProfessional>
@{ 
    Layout = null;
    int sl = 0;
}

<div class="col-md-12 text-sm">
    <table class="table table-bordered table-sm table-striped" id="tblPartsUsed">
        <thead class="btn-info">
            <tr class="text-center">
                <th>#SL</th>
                <th class="hide"></th>
                <th>Other Profession</th>
                <th>Remarks</th>
                <th class="hide">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var oth in Model)
            {
                sl = sl + 1;
                <tr>
                    <td class="text-center">@sl</td>
                    <td class="hide">@oth.OPId</td>
                    <td>@oth.Profession</td>
                    <td>@oth.Remarks</td>
                    <td class="hide">
                        <a href="#" class="btn btn-outline-warning btn-sm data-edit-model" title="Edit" data-edit-model="@oth.OPId"><i class="fas fa-pencil-alt"></i> </a>
                    </td>
                </tr>
            }
            @if (Model.Count() == 0)
            {
                <tr class="text-center empty-row">
                    <td colspan="6">
                        No Rows Found
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>