MMSLHMS/MMSLHMS/Controllers/OrganizationController.cs
using HMSBO.Models;
using HMSBO.ViewModels;
using MMSLHMS.CustomFiles.Filters;
using MMSLHMS.DAL;
using MMSLHMS.DAL.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MMSLHMS.Controllers
{
    [CustomAuthorize]
    public class OrganizationController : BaseController
    {
        // GET: Organization

        private DataContext db = new DataContext();
        public ActionResult Index()
        {
            return View();
        }

        // User By Only System Admin //
        [HttpGet]
        public ActionResult GetDepartmentList(int? OrgId, string DeptName = null) // Param DeptName is For Search funationlity throught the Ajax
        {
            if (OrgId == null || DeptName == null)
            {
                return View(); // Calling View at the first time 
            }
            else
            {
                // Retreiving data througth the AJAX Call.
                var departmentList = (from dept in db.tblDepartment
                                      join org in db.tblOrganizations on dept.OrgId equals org.OrgId
                                      select new { org.Name, org.OrgId, dept.DepartmentId, dept.DepartmentName, dept.ShortName, dept.EntryUser }).AsEnumerable();
                departmentList = departmentList.OrderBy(d => d.DepartmentName).ToList();
                if (OrgId > 0 && !string.IsNullOrEmpty(DeptName.Trim()))
                {
                    departmentList = departmentList.Where(d => d.OrgId == OrgId && d.DepartmentName.ToLower().StartsWith(DeptName.ToLower())).OrderBy(d => d.DepartmentName).ToList();
                }
                else if (OrgId > 0)
                {
                    departmentList = departmentList.Where(d => d.OrgId == OrgId).OrderBy(d => d.DepartmentName).ToList();
                }
                else if (!string.IsNullOrEmpty(DeptName.Trim()))
                {
                    departmentList = departmentList.Where(d => d.DepartmentName.ToLower().StartsWith(DeptName.ToLower())).OrderBy(d => d.DepartmentName).ToList();
                }
                return Json(departmentList, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult SaveDepartment(VmDepartment vmDepartment)
        {
            bool IsSuccess = false;
            if (ModelState.IsValid)
            {
                if (vmDepartment.DepartmentId <= 0)
                {
                    Department department = new Department();
                    department.DepartmentName = vmDepartment.DepartmentName;
                    department.ShortName = vmDepartment.ShortName;
                    department.OrgId = vmDepartment.OrgId;
                    department.EntryUser = User.UserName;
                    department.EntryDate = DateTime.Now;
                    db.tblDepartment.Add(department);
                    IsSuccess = true;
                }
                else
                {
                    var departmentInDb = db.tblDepartment.FirstOrDefault(d => d.DepartmentId == vmDepartment.DepartmentId);
                    if (departmentInDb != null)
                    {
                        departmentInDb.DepartmentName = vmDepartment.DepartmentName;
                        departmentInDb.ShortName = vmDepartment.ShortName;
                        departmentInDb.OrgId = vmDepartment.OrgId;
                        IsSuccess = true;
                    }
                }
                db.SaveChanges();
            }
            return Json(IsSuccess);
        }
        // 
        [HttpGet]
        public ActionResult GetSpecializationType(int? OrgId, string SpecType)
        {
            if (OrgId == null || SpecType == null)
            {
                return View();
            }
            else
            {
                var SpecializationType = (from st in db.tblSpecializationType
                                          join org in db.tblOrganizations on st.OrgId equals org.OrgId
                                          select new { st.Id, st.TypeName, org.OrgId, org.Name, st.EntryUser }).OrderBy(s => s.Name).ToList();

                if (OrgId > 0 && !string.IsNullOrEmpty(SpecType.Trim()))
                {
                    SpecializationType = SpecializationType.Where(s => s.OrgId == OrgId && s.TypeName.ToLower().StartsWith(SpecType.ToLower())).ToList();
                }
                else if (OrgId > 0)
                {
                    SpecializationType = SpecializationType.Where(s => s.OrgId == OrgId).ToList();
                }
                else if (!string.IsNullOrEmpty(SpecType.Trim()))
                {
                    SpecializationType = SpecializationType.Where(s => s.TypeName.ToLower().StartsWith(SpecType.ToLower())).ToList();
                }

                return Json(SpecializationType, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult SaveSpecializationType(VmSpecialization model)
        {
            bool IsSuccess = false;
            if (ModelState.IsValid)
            {
                if (model.Id <= 0)
                {
                    // Saving New Data
                    SpecializationType spType = new SpecializationType();
                    spType.OrgId = model.OrgId;
                    spType.TypeName = model.TypeName;
                    spType.EntryUser = User.UserName;
                    spType.EntryDate = DateTime.Now;
                    IsSuccess = true;
                    db.tblSpecializationType.Add(spType);
                }
                else if (model.Id > 0)
                {
                    // Editing Data..
                    var spTypeInDb = db.tblSpecializationType.FirstOrDefault(sp => sp.Id == model.Id);
                    if (spTypeInDb != null)
                    {
                        spTypeInDb.TypeName = model.TypeName;
                        spTypeInDb.OrgId = model.OrgId;
                        IsSuccess = true;
                    }
                }
                db.SaveChanges();
            }
            return Json(IsSuccess);
        }

        [HttpGet]
        public ActionResult GetDesignationList(int? OrgId, string DesigName)
        {
            if (OrgId == null || DesigName == null)
            {
                return View();
            }
            else
            {
                var designationList = (from des in db.tblDesignation
                                       join org in db.tblOrganizations on des.OrgId equals org.OrgId
                                       let OrgName = org.Name
                                       where org.OrgId == OrgId
                                       select new { des.DesigId, des.Name, des.ShortName, org.OrgId, OrgName, des.EntryUser }).OrderBy(d => d.Name).ToList();

                if (!string.IsNullOrEmpty(DesigName.Trim()))
                {
                    designationList = designationList.Where(d => d.Name.ToLower().StartsWith(DesigName.ToLower().Trim())).ToList();
                }
                return Json(designationList, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult SaveNewDesignation(VmDesignation model)
        {
            bool IsValid = false;
            if (ModelState.IsValid) // Model State
            {
                if (model.DesigId <= 0)
                {
                    Designation designation = new Designation();
                    designation.Name = model.DesignationName;
                    designation.ShortName = model.ShortName;
                    designation.OrgId = User.OrgId;
                    designation.EntryDate = DateTime.Now;
                    designation.EntryUser = User.UserName;
                    db.tblDesignation.Add(designation);
                    IsValid = true;
                }
                else if (model.DesigId > 0)
                {
                    var designationInDb = db.tblDesignation.FirstOrDefault(d => d.DesigId == model.DesigId);
                    designationInDb.Name = model.DesignationName;
                    designationInDb.ShortName = model.ShortName;
                    IsValid = true;
                }
                db.SaveChanges();
            }
            return Json(IsValid);
        }

        [HttpGet]
        public ActionResult GetBranchList()
        {
            var branch = (from b in db.tblBranchInfo
                          join o in db.tblOrganizations on b.OrgId equals o.OrgId
                          where o.OrgId == User.OrgId
                          select new { b.BranchId, b.BranchName, b.BranchCode, b.ContactNumber, b.Address, b.EntryUser, b.EntryDate, o.OrgId, o.Name,b.ShortName }).OrderByDescending(b => b.BranchId).ToList();

            IList<VmBranch> ListVmBranch = new List<VmBranch>();

            foreach (var item in branch)
            {
                VmBranch vmBranch = new VmBranch { BranchId = item.BranchId, BranchName = item.BranchName, BranchCode = item.BranchCode, ShortName=item.ShortName,ContactNumber = item.ContactNumber, Address = item.Address, EntryUser = item.EntryUser, EntryDate = item.EntryDate, OrgId = item.OrgId, OrgName = item.Name };
                ListVmBranch.Add(vmBranch);
            }

            return View(ListVmBranch);
        }

        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult SaveBranch(VmBranch model)
        {
            bool IsSuccess = false;
            if (ModelState.IsValid)
            {
                if (model.BranchId <= 0)
                {
                    Branch branch = new Branch
                    {
                        BranchName = model.BranchName,
                        BranchCode = model.BranchCode,

MMSLHMS/MMSLHMS/Views/Organization/CreateEmployee.cshtml
@model HMSBO.ViewModels.VmEmployee

@{
    /**/

    ViewBag.Title = "Create New Employee";
}
<div class="row">
    <div class="col-md-12">

    </div>
    <div class="col-md-12">
        @using (Html.BeginForm("SaveEmployee", "Organization", FormMethod.Post, new { @id = "empForm", role = "form" }))
        {
            @Html.HiddenFor(model => model.EmployeeId)
            @Html.AntiForgeryToken()
            <div class="form-row">
                <div class="form-group col-md-2">
                    <a class="btn btn-primary btn-sm" id="btnList" href="/Organization/GetEmployeeList">Back To List</a>
                </div>
                <div class="form-group col-md-8 text-center">
                    <div class="col-md-10">
                        <h4>@ViewBag.heading</h4>
                    </div>
                </div>
                <div class="form-group col-md-2">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-success btn-sm float-right"><i class="fa fa-save"></i> Save</button>
                    </div>
                </div>

            </div>
            <hr />
            <div class="form-row" style="font-size:small">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4" style="font-size:small">
                    @Html.LabelFor(model => model.MiddleName, "Middle Name", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                        @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4" style="font-size:small">
                    @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-row" style="font-size:small">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.BranchId, "Branch Name", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.BranchId, (IEnumerable<SelectListItem>)ViewBag.BrancheList, "Select Branch", new { @class = "form-control form-control-sm" })

                        @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.DepartmentId, "Department Name", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DepartmentId, (IEnumerable<SelectListItem>)ViewBag.DepartmentList, "Select Department", new { @class = "form-control form-control-sm" })
                        @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.DesignationId, "Designation", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DesignationId, (IEnumerable<SelectListItem>)ViewBag.DesignationList, "Select Designation", new { @class = "form-control form-control-sm" })
                        @Html.ValidationMessageFor(model => model.DesignationId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-row" style="font-size:small">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.MaritalStatus, "Marital Status", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.MaritalStatus,new List<SelectListItem>()
                   {
                       new SelectListItem {Text="Married",Value="Married"},
                       new SelectListItem {Text="Unmarried",Value="Unmarried"}
                   }, "Select One", new { @class = "form-control form-control-sm" })

                        @Html.ValidationMessageFor(model => model.MaritalStatus, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.Gender, "Gender", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Gender,new List<SelectListItem>()
                   {
                       new SelectListItem {Text="Male",Value="Male"},
                       new SelectListItem {Text="Female",Value="Female"}
                   }, "Select Gender", new { @class = "form-control form-control-sm" })

                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.Nationality, "Nationality", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Nationality, new List<SelectListItem>()
                   {
                       new SelectListItem {Text="Bangladeshi",Value="Bangladeshi"}
                   }, "Select One", new { @class = "form-control form-control-sm" })

                        @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-row" style="font-size:small">
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.PresentAddress, "Present Address", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.PresentAddress, new { @class = "form-control form-control-sm", @cols = "10", @rows = "3" })

                        @Html.ValidationMessageFor(model => model.PresentAddress, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.ParmanentAddress, "Parmanent Address", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.ParmanentAddress, new { @class = "form-control form-control-sm", @cols = "10", @rows = "3" })

                        @Html.ValidationMessageFor(model => model.ParmanentAddress, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-row" style="font-size:small">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.Email, "Email Address", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control form-control-sm", @type = "email" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.MobileNo, "Mobile No.", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control form-control-sm", @type = "number" } })
                        @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.HomeContactNo, "Phone Number(Home)", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HomeContactNo, new { htmlAttributes = new { @class = "form-control form-control-sm", @type = "number" } })
                        @Html.ValidationMessageFor(model => model.HomeContactNo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-row" style="font-size:small">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.DOB, "Date of Birth", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control form-control-sm", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.IsActive, "Is Active", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold", @style = "visibility:hidden" })
                    <div class="col-md-10">
                        <div class="form-control form-control-sm">
                            @Html.CheckBoxFor(model => model.IsActive) Is Active ?
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.AllowToLogin, "Allow To Login?", htmlAttributes: new { @class = "control-label col-md-10 font-weight-bold", @style = "visibility:hidden" })
                    <div class="col-md-10">
                        <div class="form-control form-control-sm">
                            @Html.CheckBoxFor(model => model.AllowToLogin) Allow To Login ?
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>


@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

        })
    </script>
}

MMSLHMS/MMSLHMS/Views/Organization/GetEmployeeList.cshtml
@model IEnumerable<HMSBO.ViewModels.VmEmployee>

@{
    ViewBag.Title = "List of Employees";
}



<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6"><h2>List of Employees</h2></div>
            <div class="col-md-6">
                <a class="btn btn-success btn-sm float-right" href="/Organization/CreateEmployee"><i class="fa fa-plus"></i> Create New Employee</a>
            </div>
        </div>
        <div class="row">
            @*style="overflow-y:scroll;height:580px"*@
            <div class="col-md-12">
                <table class="table table-bordered table-hover table-responsive" style="font-size:small;width:100%">
                    <thead>
                        <tr class="btn-info">
                            <th>
                                Employee Id
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Designation
                            </th>
                            <th>
                                Depertment
                            </th>
                            <th>
                                Branch
                            </th>
                            <th>
                                Email Address
                            </th>
                            <th>
                                Active Status
                            </th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EmployeeId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EmployeeName)
                                </td>
                                <td>

                                    @Html.DisplayFor(modelItem => item.Designation)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DepertmentName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.BranchName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ActiveStatus)
                                </td>
                                <td>
                                    <a href='@Url.Action("CreateEmployee","Organization",new {id=item.EmployeeId })' class='data-edit btn btn-circle btn-success btn-sm' ><i class='fas fa-pen' title="Edit"></i></a> |
                                    <a href="#" class="data-detail btn-sm btn btn-circle btn-warning" data-details-item="@item.EmployeeId"><i class="fas fa-list"></i></a>
                                </td>
                            </tr>
                        }
                        @if (Model.Count() == 0)
                        {
                            <tr><td colspan="6" class="text-center">No Data Found...!!!</td></tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalEmpDetail">
    <div class="modal-dialog modal-lg">
        <div class="modal-content ">
            <div class="modal-header  btn-success">
                <h4 class="modal-title" id="modalHeading">Employee Details</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div> 
            <div class="modal-body">
                @Html.AntiForgeryToken()
                <table class="table table-bordered table-responsive-lg emp-details">
                    <tr>
                        <td>First Name</td>
                        <td class="font-weight-bold"><label class="firstName"></label></td>
                        <td>Middle Name</td>
                        <td class="font-weight-bold"><label class="middleName"></label></td>
                    </tr>
                    <tr>
                        <td>Last Name</td>
                        <td class="font-weight-bold"><label class="lastName"></label></td>
                        <td>Branch Name</td>
                        <td class="font-weight-bold"><label class="branch"></label></td>
                    </tr>
                    <tr>
                        <td>Department</td>
                        <td class="font-weight-bold"><label class="department"></label></td>
                        <td>Designation</td>
                        <td class="font-weight-bold"><label class="designation"></label></td>
                    </tr>
                    <tr>
                        <td>Marital Status</td>
                        <td class="font-weight-bold"><label class="maritalStatus"></label></td>
                        <td>Gender</td>
                        <td class="font-weight-bold"><label class="gender"></label></td>
                    </tr>
                    <tr>
                        <td>Nationality</td>
                        <td class="font-weight-bold"><label class="nationality"></label></td>
                        <td>Parmanent Address</td>
                        <td class="font-weight-bold">
                            <label class="parmanentAdd"></label>
                        </td>
                    </tr>
                    <tr>
                        <td>Present Address</td>
                        <td class="font-weight-bold"><label class="presentAdd"></label></td>
                        <td>Email</td>
                        <td class="font-weight-bold"><label class="email"></label></td>
                    </tr>
                    <tr>
                        <td>Mobile No.</td>
                        <td class="font-weight-bold"><label class="mobile"></label></td>
                        <td>Home Contact No.</td>
                        <td class="font-weight-bold"><label class="homeContact"></label></td>
                    </tr>
                    <tr>
                        <td>Date of Birth</td>
                        <td class="font-weight-bold"><label class="dob"></label></td>
                        <td>Is Active?</td>
                        <td class="font-weight-bold"><label class="active"></label></td>
                    </tr>
                    <tr>
                        <td>Allow to login?</td>
                        <td class="font-weight-bold" colspan="3"><label class="allowLogin"></label></td>
                    </tr>
                </table>
            </div>
           
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

        })

        $(document).on("click", "a.data-detail", function (e) {
            e.preventDefault();
            clearLabel()
            $("#modalEmpDetail").modal();
            var empId = $(this).parent().parents('tr').find('td:eq(0)').html()
           
            $.when(postReqWithToken(dataType.applicationJson, dataType.json, 'POST', '/Organization/GetEmployeeDetails', JSON.stringify({ id: empId }), getToken())).then(function (res) {
                //console.log('Server Data');
                //console.log("-----------");
                //console.log(res);
                $("label.firstName").text(res[0].firstName);
                $("label.middleName").text(res[0].middleName);
                $("label.lastName").text(res[0].lastName);
                $(".branch").text(res[0].branch);
                $(".department").text(res[0].department);
                $(".designation").text(res[0].designation);
                $(".maritalStatus").text(res[0].maritalStatus);
                $(".gender").text(res[0].gender);
                $(".nationality").text(res[0].nationality);
                $(".parmanentAdd").text(res[0].parmanentAdd);
                $(".presentAdd").text(res[0].presentAdd);
                $(".email").text(res[0].email);
                $(".mobile").text(res[0].mobile);
                $(".homeContact").text(res[0].homeContact);
                var dob = new Date(parseInt(res[0].dob.replace("/Date(", "").replace(")/", ""), 10));
                var day = (dob.getDate().toString().length > 1 ? dob.getDate().toString() : '0' + dob.getDate().toString());
                var dateData = day +'-'+ (getMonthName(dob.getMonth(), "MMM"))+'-'+ dob.getFullYear();
                $(".dob").text(dateData);
                $(".active").text((res[0].active== true ? "Active":"Inactive"));
                $(".allowLogin").text((res[0].allowLogin == true ? "Yes" : "No"));

            }).fail(function (err) {
                console.log(err);
            })
        })

        function clearLabel() {
            $("table.emp-details label").text('');
        }

        $('#modalEmpDetail').on('hidden.bs.modal', function (e) {
            //clearLabel();
        })
    </script>    
}