MMSLHMS/MMSLHMS/Controllers/AppoinmentController.cs
using HMSBO.Models;
using HMSBO.ReportModels;
using HMSBO.ViewModels;
using Microsoft.Reporting.WebForms;
using MMSLHMS.CustomFiles.Filters;
using MMSLHMS.DAL;
using MMSLHMS.DAL.Security;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MMSLHMS.Controllers
{
    [CustomAuthorize]
    public class AppoinmentController : BaseController
    {
        private DataContext db = new DataContext();
        // GET: Appoinment
        #region Doctors
        [HttpGet]
        public ActionResult GetDoctorList(string flag,string doctorName,string specialist, string mobile,string sex)
        {
            if (string.IsNullOrEmpty(flag))
            {
                ViewBag.ddlSpecialist = db.tblSpecialists.Select(s => new SelectListItem { Text = s.Specialization, Value = s.Specialization }).ToList();
                ViewBag.txtDoctorName = db.tblDoctors.Select(s => new SelectListItem { Text = s.DocName, Value = s.DocName }).ToList();
                return View();
            }
            else
            {
                var doctor = db.tblDoctors.Where(d=>d.OrgId==User.OrgId && (doctorName == null || doctorName.Trim() == "" || d.DocName.ToLower().Contains(doctorName.ToLower().Trim())) && (specialist == null || specialist.Trim() == "" || d.DocSpecialist.ToLower().Contains(specialist.ToLower().Trim())) && (mobile == null || mobile.Trim() == "" || d.DocMobile.ToLower().Contains(mobile.ToLower().Trim())) && (sex == null || sex.Trim() == "" || d.Sex.ToLower().Contains(sex.ToLower().Trim()))).ToList();
                List<VmDoctors> doctors = new List<VmDoctors>();
                foreach(var item in doctor)
                {
                    VmDoctors vm = new VmDoctors();
                    vm.DocId = item.DocId;
                    vm.DocName = item.DocName;
                    vm.DocDegree = item.DocDegree;
                    vm.DocRegNo = item.DocRegNo;
                    vm.DocAddress = item.DocAddress;
                    vm.DocType = item.DocType;
                    vm.DocSpecialist = item.DocSpecialist;
                    vm.DocMobile = item.DocMobile;
                    vm.DocEmail = item.DocEmail;
                    vm.HospitalName = item.HospitalName;
                    vm.Remarks = item.Remarks;
                    vm.GenerelFee = item.GenerelFee;
                    vm.ReportFee = item.ReportFee;
                    vm.CounselingFee = item.CounselingFee;
                    vm.FollowUpFee = item.FollowUpFee;
                    vm.Sex = item.Sex;
                    vm.DOB = item.DOB;
                    doctors.Add(vm);
                }
                return PartialView("_GetDoctorList", doctors);
            }
        }

        public ActionResult CreateDoctor()
        {
            ViewBag.ddlSpecialist = db.tblSpecialists.Select(s => new SelectListItem { Text = s.Specialization, Value = s.Specialization }).ToList();

            ViewBag.ddlOtherProfession = db.tblOtherProfessional.Select(s => new SelectListItem { Text = s.Profession, Value = s.Profession }).ToList();

            ViewBag.ddlStartTime = db.tblTimes.Select(s => new SelectListItem { Text = s.ScendTimeF, Value = s.Time.ToString() }).ToList();

            ViewBag.ddlEndTime = db.tblTimes.Select(s => new SelectListItem { Text = s.ScendTimeF, Value = s.Time.ToString() }).ToList();
            return View();
        }

        public ActionResult SaveDoctorProfile(VmDoctors model)
        {
            bool IsSuccess = false;
            if (ModelState.IsValid)
            {
                Doctor doctor = new Doctor();
                doctor.DocName = model.DocName;
                doctor.DocDegree = model.DocDegree;
                doctor.DocRegNo = model.DocRegNo;
                doctor.DocAddress = model.DocAddress;
                doctor.DocType = model.DocType;
                doctor.DocSpecialist = model.DocSpecialist;
                doctor.DocMobile = model.DocMobile;
                doctor.DocEmail = model.DocEmail;
                doctor.HospitalName = model.HospitalName;
                doctor.Remarks = model.Remarks;
                doctor.GenerelFee = model.GenerelFee;
                doctor.ReportFee = model.ReportFee;
                doctor.FollowUpFee = model.FollowUpFee;
                doctor.CounselingFee = model.CounselingFee;
                doctor.OtherProfession = model.OtherProfession;
                doctor.Sex = model.Sex;
                doctor.DOB = model.DOB;
                doctor.EntryUser = User.UserName;
                doctor.EntryDate = DateTime.Now;
                doctor.OrgId = User.OrgId;
                //if (model.DoctorImage != null)
                //{
                //    doctor.DocImage = Utility.SaveImage(model.DoctorImage.InputStream, model.DoctorImage.FileName, Utility.DoctorImage, User.OrgId);
                //}

                List<DoctorDetails> detailslist = new List<DoctorDetails>();
                foreach (var item in model.doctorDetails)
                {
                    DoctorDetails details = new DoctorDetails
                    {
                        DocName = model.DocName,
                        DocSpecialist = model.DocSpecialist,
                        DocDegree = model.DocDegree,
                        GenerelFee = model.GenerelFee,
                        DocMobile = model.DocMobile,
                        Day = item.Day,
                        DayOfTime = item.DayOfTime,
                        StartTime = item.StartTime,
                        EndTime = item.EndTime,
                        EntryUser = User.UserName,
                        EntryDate = DateTime.Now,
                        OrgId = User.OrgId
                    };
                    detailslist.Add(details);
                }
                doctor.DoctorDetails = detailslist;
                db.tblDoctors.Add(doctor);
                IsSuccess = true;
                db.SaveChanges();
            }
            return Json(IsSuccess);
        }
        public ActionResult SaveDoctorFile(VmDoctors model)
        {
            bool IsSuccess = false;
            var dt = db.tblDoctors.Where(d => d.OrgId == User.OrgId).ToList();
            var dot = dt.LastOrDefault().DocId;
            if (dot > 0 && model.DoctorImage != null)
            {
                var docctor = db.tblDoctors.Where(d => d.DocId == dot && d.OrgId == User.OrgId).FirstOrDefault();
                docctor.DocImage = Utility.SaveImage(model.DoctorImage.InputStream, model.DoctorImage.FileName, Utility.DoctorImage, User.OrgId);
                IsSuccess = true;
                db.SaveChanges();
            }
            return Json(IsSuccess);
        }

        public ActionResult DoctorScheduleList(string flag,string name,string specialist,string days,string shift)
        {
            if (string.IsNullOrEmpty(flag))
            {
                ViewBag.ddlDoctorName = db.tblDoctors.Where(d => d.OrgId == User.OrgId).Select(d => new SelectListItem { Text = d.DocName, Value = d.DocName }).ToList();
                ViewBag.ddlSpecialist = db.tblSpecialists.Where(s=>s.OrgId==User.OrgId).Select(s => new SelectListItem { Text = s.Specialization, Value = s.Specialization }).ToList();
                return View();
            }
            else
            {
                var doctorDetails = db.tblDoctorDetails.Where(d => d.OrgId == User.OrgId && (name == null || name.Trim() == "" || d.DocName.ToLower().Contains(name.ToLower().Trim())) && (specialist == null || specialist.Trim() == "" || d.DocSpecialist.ToLower().Contains(specialist.ToLower().Trim())) && (days == null || days.Trim() == "" || d.Day.ToLower().Contains(days.ToLower().Trim())) && (shift == null || shift.Trim() == "" || d.DayOfTime.ToLower().Contains(shift.ToLower().Trim())) ).ToList();
                List<VmDoctorDetails> list = new List<VmDoctorDetails>();
                foreach(var item in doctorDetails)
                {
                    VmDoctorDetails details = new VmDoctorDetails()
                    {
                        DocName=item.DocName,
                        DocDegree=item.DocDegree,
                        DocSpecialist=item.DocSpecialist,
                        DocMobile=item.DocMobile,
                        GenerelFee=item.GenerelFee,
                        Day=item.Day,
                        DayOfTime=item.DayOfTime,
                        StartTime=item.StartTime,
                        EndTime=item.EndTime
                    };
                    list.Add(details);
                }
                return PartialView("_DoctorScheduleList", list);
            }
        }

        public ActionResult DoctorTimeDetails(long docId)
        {
            var doctorTime = db.tblDoctorDetails.Where(d => d.DocId == docId).ToList();
            List<VmDoctorDetails> doclist = new List<VmDoctorDetails>();
            foreach(var item in doctorTime)
            {
                VmDoctorDetails details = new VmDoctorDetails
                {
                    DocName = item.DocName,
                    DocSpecialist = item.DocSpecialist,
                    DocDegree = item.DocDegree,
                    DocMobile = item.DocMobile,
                    Day = item.Day,
                    DayOfTime=item.DayOfTime,
                    StartTime=item.StartTime,
                    EndTime=item.EndTime,
                };
                doclist.Add(details);
            }
            return PartialView("_DoctorTimeDetails", doclist);
        }
        #endregion

        #region - Base64 Image String
        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult GetImageBase64String(long docId)
        {
            string docImg = string.Empty;
            try
            {
                if (docId > 0)
                {
                    var alldoctor = db.tblDoctors.Where(o => o.DocId == docId).ToList();

MMSLHMS/MMSLHMS/Views/Appoinment/CreateAppoinment.cshtml
@{
    ViewBag.Title = "CreateAppoinment";
}

<div class="row">
    <div class="col-md-12 text-center">
        <div class="card card-gray shadow">
            <div class="card-header">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4 text-left">
                            <a href="/Appoinment/GetAppoinmentList" class="btn btn-sm btn-outline-primary" title="Back To List"><i class="fas fa-arrow-alt-circle-left"></i></a>
                        </div>
                        <div class="col-md-4 text-center">
                            <h4><b>Create New Appoinment</b></h4>
                        </div>
                        <div class="col-md-4 hide">
                            <button class="btn btn-outline-danger btn-sm float-lg-right" id="btnReset" title="RESET UI"><i class="fas fa-sync-alt"></i> </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card shadow">
            <div class="card-header">
                @Html.AntiForgeryToken()
                <div class="row text-sm">
                    <div class="col-md-3">
                        <div class="form-group col-md-12">
                            <label for="ddlDoctorName" class="control-label font-weight-bold">Doctor Name</label>
                            @Html.DropDownList("ddlDoctorName", (IEnumerable<SelectListItem>)ViewBag.ddlDoctorName, "--Select Doctor--", new { @class = "form-control form-control-sm select2 select2bs4 search-control" })
                            <span class="error hide require-doctorName font-weight-bold">Specialist is required !</span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group col-md-12">
                            <label for="txtPatientName" class="control-label font-weight-bold">Patient Name</label>
                            <input type="text" name="Patient" value="" id="txtPatientName" placeholder="Input Patient Name" class="form-control form-control-sm search-control" />
                            <span class="error hide require-patientName font-weight-bold">Patient is required !</span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group col-md-12">
                            <label for="txtPatientAddress" class="control-label font-weight-bold">Address</label>
                            <input type="text" name="Address" value="" id="txtPatientAddress" placeholder="Input Patient Address" class="form-control form-control-sm search-control" />
                            <span class="error hide require-Address font-weight-bold">Address is required !</span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group col-md-12">
                            <label for="txtPatientMobile" class="control-label font-weight-bold">Patient Mobile</label>
                            <input type="text" name="mobile" value="" id="txtPatientMobile" placeholder="Input Mobile No" class="form-control form-control-sm search-control" />
                            <span class="error hide require-Mobile font-weight-bold">Mobile is required !</span>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="form-group col-md-12">
                            <label for="txtPatientAge" class="control-label font-weight-bold">Age</label>
                            <input type="text" name="mobile" value="" id="txtPatientAge" placeholder="Input Age" class="form-control form-control-sm search-control" />
                            <span class="error hide require-Mobile font-weight-bold">Age is required !</span>
                        </div>
                    </div>
                </div>
                <div class="row text-sm">
                    <div class="col-md-3">
                        <div class="form-group col-md-12">
                            <label for="txtShifTime" class="control-label font-weight-bold">Shift</label>
                            <select id="txtShifTime" name="docType" class="form-control form-control-sm select2 select2bs4">
                                <option value="">--Selecet One--</option>
                                <option value="Morning">Morning</option>
                                <option value="Evening">Evening</option>
                                <option value="AllDay">AllDay</option>
                            </select>
                            <span class="error hide require-shiftTime font-weight-bold">Hospital is required !</span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group col-md-12">
                            <label for="txtStatestatus" class="control-label font-weight-bold">State Status</label>
                            <select id="txtStatestatus" name="status" class="form-control form-control-sm select2 select2bs4">
                                <option value="">--Selecet One--</option>
                                <option value="New Patient">New Patient</option>
                                <option value="Report">Report</option>
                                <option value="Follow Up">Follow Up</option>
                                <option value="Conseling">Conseling</option>
                            </select>
                            <span class="error hide require-StateSatus font-weight-bold">Status is required !</span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group col-md-12">
                            <label for="dptAppoinmentDate" class="control-label font-weight-bold">Appoinment Date</label>
                            <input type="date" name="appoinDate" value="" id="dptAppoinmentDate" class="form-control form-control-sm search-control" />
                            <span class="error hide require-Address font-weight-bold">Date is required !</span>
                        </div>
                    </div>
                    <div class="col-md-3 text-right">
                        <label for="" class="control-label font-weight-bold" style="visibility:hidden"> Adddddddddddddddddddddd</label>
                        <div class="clearfix">
                            <button type="submit" class="btn btn-sm btn-success float-lg-right mr-1" id="btnSubmit" title="Make Appoinment"><i class="fas fa-plus"></i> Save Appoinment</button>
                        </div>
                    </div>
                </div>
            </div>
         </div>
     </div>
 </div>
@section Scripts{
    <script type="text/javascript">
        var ddlDoctorName = $("#ddlDoctorName");
        var txtPatientName = $("#txtPatientName");
        var txtPatientAddress = $("#txtPatientAddress");
        var txtPatientMobile = $("#txtPatientMobile");
        var txtShifTime = $("#txtShifTime");
        var txtStatestatus = $("#txtStatestatus");
        var dptAppoinmentDate = $("#dptAppoinmentDate");
        var txtPatientAge = $("#txtPatientAge");

        $(document).ready(function () {
            $('.select2').select2();

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'classic'
            });
        })
        function validateInput() {
            $('.error').addClass('hide');
            var isValid = true;
            if ($.trim(ddlDoctorName.val()) == "") {
                $(".require-doctorName").removeClass("hide");
                isValid = false;
            }
            if ($.trim(txtPatientName.val()) == "") {
                $(".require-patientName").removeClass("hide");
                isValid = false;
            }
            return isValid;
        }


        $("#btnSubmit").click(function (e) {
            e.preventDefault();
            $('.error').addClass('hide');
            if (validateInput() == true) {
                    var appoinment = {
                        DoctorName: ddlDoctorName.val(),
                        PatientName: txtPatientName.val(),
                        PatientAddress: txtPatientAddress.val(),
                        PatientMobile: txtPatientMobile.val(),
                        SateStatus: txtStatestatus.val(),
                        Shift: txtShifTime.val(),
                        AppoinmentDate: dptAppoinmentDate.val(),
                        Age: txtPatientAge.val(),

                    }
                    var data = JSON.stringify({ model: appoinment });
                    //return console.log(data);
                    
                    $.when(postReqWithToken(dataType.applicationJson, dataType.json, 'POST', '/Appoinment/SaveAppoinment', data, getToken())).then(function (res, status) {
                        if (res == true) {
                            alert(execuStatus.successSave);

                                setTimeout(function () {
                                    redirectPage('@Url.Action("GetAppoinmentList")');
                                }, 1000);
                            }
                            else {
                            alert(execuStatus.fail);
                            }
                    }).fail(function (err) {
                        alert(execuStatus.fail);
                    })
                }
        });

        function redirectPage(page) {
            window.location.replace(page);
        }
    </script>
    }

MMSLHMS/MMSLHMS/Views/Appoinment/GetAppoinmentList.cshtml
@{
    ViewBag.Title = "GetAppoinmentList";
}

<div class="row">
    <div class="col-md-12 text-center">
        <div class="card card-gray shadow">
            <div class="card-header">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4 text-left">

                        </div>
                        <div class="col-md-4 text-center">
                            <h5><b>Get All Appoinment List</b></h5>
                        </div>
                        <div class="col-md-4">
                            <a href="/Appoinment/CreateAppoinment" class="btn btn-outline-primary btn-sm float-lg-right" id="btnAddNew"><i class="fa fa-plus"></i> Create New Appointment</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        @using (Html.BeginForm("GetAppoinmentListReport", "Appoinment", FormMethod.Get, new { @target = "_blank" }))
                        {
                            <form id="frmLstInvestigation" method="get">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <label for="ddlDoctorName" class="control-label font-weight-bold">Doctor Name</label>
                                            @Html.DropDownList("ddlDoctorName", (IEnumerable<SelectListItem>)ViewBag.ddlDoctorName, "Search By Doctor", new { @class = "form-control form-control-sm select2 select2bs4 search-control" })
                                        </div>
                                        <div class="col-md-2">
                                            <label for="txtShifTime" class="control-label font-weight-bold">Shift</label>
                                            <select id="txtShifTime" name="shift" class="form-control form-control-sm select2 select2bs4">
                                                <option value="">Search By Shift</option>
                                                <option value="Morning">Morning</option>
                                                <option value="Evening">Evening</option>
                                                <option value="AllDay">AllDay</option>
                                            </select>
                                        </div>
                                        <div class="col-md-2">
                                            <label class="control-label font-weight-bold" for="dtpFromDateFortab1">From Date</label>
                                            <input type="date" class="form-control form-control-sm" id="dtpFromDateFortab1" name="fromDate" />
                                        </div>
                                        <div class="col-md-2">
                                            <label class="control-label font-weight-bold" for="dtpToDateFortab1">To Date</label>
                                            <input type="date" class="form-control form-control-sm" id="dtpToDateFortab1" name="toDate" />
                                        </div>
                                        <div class="col-md-2">
                                            <label class="control-label font-weight-bold" for="txtPatientName">Patient Name</label>
                                            <input type="text" class="form-control form-control-sm" placeholder="Search By Patient Name" id="txtPatientName" name="name" />
                                        </div>
                                        <div class="col-md-2">
                                            <label class="control-label font-weight-bold" for="txtPatientMobile">Patient Mobile</label>
                                            <input type="text" class="form-control form-control-sm" placeholder="Search By Patient Mobile" id="txtPatientMobile" name="mobile" />
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-2" id="divReportType">
                                            <label class="control-label font-weight-bold" for="rptType">Type</label>
                                            <select name="rptType" id="rptType" class="form-control form-control-sm">
                                                <option value="PDF">PDF</option>
                                                <option value="EXCEL">EXCEL</option>
                                            </select>
                                        </div>
                                        <div class="col-md-1" id="divbtnReport">
                                            <label class="control-label font-weight-bold" for="Download" style="visibility:hidden">Download</label>
                                            <button type="submit" title="Download Dealer Receipt" class="btn btn-sm btn-outline-danger"><i class="fas fa-file-pdf"> </i></button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="col-md-12 text-sm" id="dataContainer">
        @{Html.RenderAction("GetAppoinmentList", new { flag = "view" });}
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        var ddlDoctorName = $("#ddlDoctorName");
        var txtShifTime = $("#txtShifTime");
        var dtpFromDateFortab1 = $("#dtpFromDateFortab1");
        var dtpToDateFortab1 = $("#dtpToDateFortab1");
        var txtPatientName = $("#txtPatientName");
        var txtPatientMobile = $("#txtPatientMobile");

        $(document).ready(function () {
            $('.select2').select2();

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'classic'
            });
        })

        ddlDoctorName.change(function () {
            LoadDataTable();
        })
        txtShifTime.change(function () {
            LoadDataTable();
        })
        dtpFromDateFortab1.change(function () {
            LoadDataTable();
        })
        dtpToDateFortab1.change(function () {
            LoadDataTable();
        })
        txtPatientName.keyup(function () {
            LoadDataTable();
        })
        txtPatientMobile.keyup(function () {
            LoadDataTable();
        })
        function LoadDataTable() {
            var data = { flag: "search", doctorName: ddlDoctorName.val(), shift: txtShifTime.val(), fromDate: dtpFromDateFortab1.val(), toDate: dtpToDateFortab1.val(), patientName: txtPatientName.val().trim(), patientMobile: txtPatientMobile.val().trim() };

            //return console.log(data);
            $.when(getReqWithData('html', 'GET', '/Appoinment/GetAppoinmentList', data)).then(function (res, status) {
                console.log(status);
                if (status === "success") {
                    $("#dataContainer").fadeOut('500', function () {
                        $("#dataContainer").empty();
                        $("#dataContainer").append(res).fadeIn('500');
                    });
                }
            }).fail(function (error) {
                console.log(error);
            });
        }
    </script>
    }

MMSLHMS/MMSLHMS/Views/Appoinment/_DoctorScheduleList.cshtml
@model IEnumerable<HMSBO.ViewModels.VmDoctorDetails>
@{ 
    Layout = null;
    int sl = 0;
}
<div class="col-md-12 text-sm" style="overflow-y:scroll">
    <table class="table table-bordered table-sm table-striped" id="tblPartsUsed">
        <thead class="btn-info">
            <tr class="text-center">
                <th style="vertical-align:middle">#SL</th>
                <th class="hide"></th>
                <th style="vertical-align:middle">Dr. Name</th>
                <th style="vertical-align:middle">Mobile No</th>
                <th style="vertical-align:middle">Degree</th>
                <th style="vertical-align:middle">Specialist</th>
                <th style="vertical-align:middle">Day</th>
                <th style="vertical-align:middle">Shift</th>
                <th style="vertical-align:middle">Start Time</th>
                <th style="vertical-align:middle">End Time</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                sl = sl + 1;
                <tr>
                    <td class="text-center">@sl</td>
                    <td class="hide">@item.TDId</td>
                    <td>@item.DocName</td>
                    <td>@item.DocMobile</td>
                    <td>@item.DocDegree</td>
                    <td>@item.DocSpecialist</td>
                    <td>@item.Day</td>
                    <td>@item.DayOfTime</td>
                    <td>@item.StartTime</td>
                    <td>@item.EndTime</td>
                </tr>
            }
            @if (Model.Count() == 0)
            {
                <tr class="text-center empty-row">
                    <td colspan="9">
                        No Rows Found
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MMSLHMS/MMSLHMS/Views/Appoinment/_DoctorTimeDetails.cshtml
@model IEnumerable<HMSBO.ViewModels.VmDoctorDetails>
@{ 
    Layout = null;
    int sl = 0;
}
<table class="table table-bordered table-sm table-striped">
    <tbody>
        <tr class="text-center">
            <th style="color: lightcoral">Doctor Name:</th>
            <th>@Model.FirstOrDefault().DocName</th>
            <th style="color:lightcoral">Specialist:</th>
            <th>@Model.FirstOrDefault().DocSpecialist</th>
            <th style="color:lightcoral">Mobile:</th>
            <th>@Model.FirstOrDefault().DocMobile</th>
        </tr>
    </tbody>
</table>
<div class="col-md-12 text-sm">
    <table class="table table-bordered table-sm table-striped" id="tblPartsUsed">
        <thead class="btn-info">
            <tr class="text-center">
                <th style="vertical-align:middle">#SL</th>
                <th style="vertical-align:middle">Day</th>
                <th style="vertical-align:middle">Shift</th>
                <th style="vertical-align:middle">Start Time</th>
                <th style="vertical-align:middle">End Time</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                sl = sl + 1;
                <tr>
                    <td class="text-center">@sl</td>
                    <td class="text-center">@item.Day</td>
                    <td class="text-center">@item.DayOfTime</td>
                    <td class="text-center">@item.StartTime</td>
                    <td class="text-center">@item.EndTime</td>
                </tr>
            }
            @if (Model.Count() == 0)
            {
                <tr class="text-center empty-row">
                    <td colspan="9">
                        No Rows Found
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>